[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['account-abstraction/=lib/account-abstraction/contracts/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config